# @package _global_
# For a small profitmax run

seed: 8675309
name: profitmax_small

# fish params
fish_params:
  B0: 180
  k: &max_pop 200  # The max population
  r: 0.4
  qE:
    lower: 0.2
    upper: 0.8

world_sim:
  real_horizon: 40  # How long to run for
  plan_horizon: 40  # Planning horizon
  n_montecarlo: 5

# Parameters outside the world sim
run_params:
  num_param_batches: 20
  omega:
    min: 0
    max: 0.3
    step: 0.1

# Action Models
DE_dynamics:
  model: "EulerMaruyamaDynamics"
  t_end: 1
  num_points: 10
  D: 1.0
  max_b: *max_pop
revenue:
  model: "RevenueModel"
  P0: 1.2
  rho: -0.8
cost:
  model: "CostModel"
  C0: 1.2
  gamma: -0.5
policy:
  model: "ProfitMaximizingPolicy"
loss:
  model: "NoisyLossModel"
  scale: 0.1
preference_prior:
  model: "SigmoidPreferencePrior"
  l_bar: 0.
  p_star: 0.5
  l_star: 1.0
risk:
  model: "DifferentialEntropyRiskModel"
