# @package _global_
seed: 8675309
name: ""
log_level: INFO

# fish params
fish_params:
  B0: 180
  k: &max_pop 200  # The max population
  r: 0.4
  qE:
    step: 0.1

world_sim:
  real_horizon: 1   # How long to run for
  plan_horizon: 20  # Planning horizon
  n_montecarlo: 1

# Parameters outside the world sim
run_params:
  num_param_batches: 1
  lmbda:
    min:
      - 200.
    max:
      - 500.
    step:
      - 10.0

# Action Models
DE_dynamics:
  model: "EulerMaruyamaDynamics"
  t_end: 1
  num_points: 10
  D: 0.0
  max_b: *max_pop
revenue:
  model: "RevenueModel"
  P0: 0.2
  rho: -0.5
cost:
  model: "CostModel"
  C0: 2.0
  gamma: -0.5
  max_cost: &max_cost 30
policy:
  model: "APrioriPolicy"
loss:
  model: "LossModel"
preference_prior:
  model: "ExponentialPreferencePrior"
  l_bar: *max_cost  # Maximum loss
  p_star: 0.5
  l_star: 0.1
risk:
  model: "DifferentialEntropyRiskModel"
