# @package _global_
seed: 8675309
name: "const-exp"
log_level: INFO

# fish params
fish_params:
  B0: 180
  k: &max_pop 200  # The max population
  r: 0.4
  qE:
    lower: 0.45
    upper: 0.55

world_sim:
  real_horizon: 40  # How long to run for
  plan_horizon: 20  # Planning horizon
  n_montecarlo: 10

# Parameters outside the world sim
run_params:
  num_param_batches: 100
  omega:
    - 0.
    - 0.1
    - 0.5
    - 1.0

# Action Models
DE_dynamics:
  model: "EulerMaruyamaDynamics"
  t_end: 1
  num_points: 10
  D: 1.0
  max_b: *max_pop
revenue:
  model: "RevenueModel"
  P0: 0.5
  rho: -0.5
cost:
  model: "CostModel"
  C0: &max_cost 1.0
  gamma: -0.5
policy:
  model: "ConstantPolicy"
loss:
  model: "NoisyLossModel"
  scale: 0.1
preference_prior:
  model: "ExponentialPreferencePrior"
  l_bar: *max_cost  # Maximum loss
  p_star: 0.5
  l_star: *max_cost
risk:
  model: "DifferentialEntropyRiskModel"
